// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Roamy.Server.Data;

#nullable disable

namespace Roamy.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260406224905_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Roamy.Shared.Models.Activity", b =>
                {
                    b.Property<Guid>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DayId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("interval");

                    b.Property<Guid?>("LocationActivityLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("interval");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("ActivityId");

                    b.HasIndex("DayId");

                    b.HasIndex("LocationActivityLocationId");

                    b.HasIndex("TripId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Roamy.Shared.Models.ActivityLocation", b =>
                {
                    b.Property<Guid>("ActivityLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<Guid>("AreaTripLocationId")
                        .HasColumnType("uuid");

                    b.HasKey("ActivityLocationId");

                    b.HasIndex("AreaTripLocationId");

                    b.ToTable("ActivityLocations");
                });

            modelBuilder.Entity("Roamy.Shared.Models.Day", b =>
                {
                    b.Property<Guid>("DayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<string>("Weather")
                        .HasColumnType("text");

                    b.HasKey("DayId");

                    b.HasIndex("TripId");

                    b.ToTable("Days");
                });

            modelBuilder.Entity("Roamy.Shared.Models.Trip", b =>
                {
                    b.Property<Guid>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TripId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("Roamy.Shared.Models.TripLocation", b =>
                {
                    b.Property<Guid>("TripLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("TripLocationId");

                    b.HasIndex("TripId");

                    b.ToTable("TripLocations");
                });

            modelBuilder.Entity("Roamy.Shared.Models.Activity", b =>
                {
                    b.HasOne("Roamy.Shared.Models.Day", null)
                        .WithMany("Activities")
                        .HasForeignKey("DayId");

                    b.HasOne("Roamy.Shared.Models.ActivityLocation", "Location")
                        .WithMany()
                        .HasForeignKey("LocationActivityLocationId");

                    b.HasOne("Roamy.Shared.Models.Trip", null)
                        .WithMany("Shortlist")
                        .HasForeignKey("TripId");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Roamy.Shared.Models.ActivityLocation", b =>
                {
                    b.HasOne("Roamy.Shared.Models.TripLocation", "Area")
                        .WithMany()
                        .HasForeignKey("AreaTripLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Roamy.Shared.Models.Day", b =>
                {
                    b.HasOne("Roamy.Shared.Models.Trip", null)
                        .WithMany("Days")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Roamy.Shared.Models.TripLocation", b =>
                {
                    b.HasOne("Roamy.Shared.Models.Trip", null)
                        .WithMany("Location")
                        .HasForeignKey("TripId");
                });

            modelBuilder.Entity("Roamy.Shared.Models.Day", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("Roamy.Shared.Models.Trip", b =>
                {
                    b.Navigation("Days");

                    b.Navigation("Location");

                    b.Navigation("Shortlist");
                });
#pragma warning restore 612, 618
        }
    }
}
